### ISSUE TITLE
fontspec error: "font-not-found" The font "TeX Gyre Termes" cannot be found. 

### ISSUE THREAD

**Issue by hairuo** [ZJU-Awesome/write_with_LaTeX#10]
系统: MacOS 10.13.6
TeX: MacTex 2018
编辑器: TeXStudio
问题描述：Windows7下编译通过，Mac下编译报错.
具体内容包括: fontspec error: "font-not-found" The font "TeX Gyre Termes" cannot be found.
[thesis.log](https://github.com/ZJU-Awesome/write_with_LaTeX/files/2990793/thesis.log)

**Comment by muzimuzhi** [comment]
TeX Gyre Termes 字体是通过 latex 发行版安装的，没有装到系统字体目录里。
* win 下，xelatex 能直接使用发行版里的字体
* macOS 下，不能

解决方案可见这篇[知乎文章](https://zhuanlan.zhihu.com/p/59774395)。

PS：展示 log 信息时，应该上传文件，不应该贴完整文本。

**Comment by muzimuzhi** [comment]
建议把 issue 里的完整 log 文本编辑掉，以便利后来者阅读。

**Comment by hairuo** [comment]
> TeX Gyre Termes 字体是通过 latex 发行版安装的，没有装到系统字体目录里。
> 
> * win 下，xelatex 能直接使用发行版里的字体
> * macOS 下，不能
> 
> 解决方案可见这篇[知乎文章](https://zhuanlan.zhihu.com/p/59774395)。
> 
> PS：展示 log 信息时，应该上传文件，不应该贴完整文本。

谢谢回复，按照知乎文章的创建软链接关联，正常了。
另外，log文件内容已经删除，修改为附件上传，谢谢提醒（很抱歉第一次贴log没经验）。
