### ISSUE TITLE
为何作者、指导老师还有学号在源文件中填写了，生成的pdf缺依然是空白？

### ISSUE THREAD

**Issue by grasshopyx** [ZJU-Awesome/write_with_LaTeX#8]
这个问题出现在封面。
我发现在源代码中，即使填写了 author, supervisor, submitdate, studentnumber这些命令的内容，编译出来的pdf依然是空白的。但是专业名称、研究方向、所在学院这些栏目都没有问题。
事实上，模板的原文件这些内容也填写了，编译出来对应的也是空白。

自己解决：其实是 documentclass 的问题，把 anon 去掉就好了

**Comment by hairuo** [comment]
谢谢，看起来anon = anonymous.
